### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zhihui2015** [CURTLab/LVGLBuilder#12]
E:\github\LVGLBuilder\LVGLProject.cpp:49: error: C2676: 二进制“[”:“QJsonDocument”不定义该运算符或到预定义运算符可接收的类型的转换

E:\github\LVGLBuilder\LVGLProject.cpp:61: error: C2676: 二进制“[”:“QJsonDocument”不定义该运算符或到预定义运算符可接收的类型的转换

E:\github\LVGLBuilder\LVGLProject.cpp:72: error: C2676: 二进制“[”:“QJsonDocument”不定义该运算符或到预定义运算符可接收的类型的转换

E:\github\LVGLBuilder\LVGLProperty.cpp:289: error: C2027: 使用了未定义类型“QDebug”

E:\github\LVGLBuilder\LVGLProperty.cpp:289: error: C2678: 二进制“<<”: 没有找到接受“QDebug”类型的左操作数的运算符(或没有可接受的转换)

E:\github\LVGLBuilder\LVGLProperty.cpp:289: error: C2088: “<<”: 对于 class 非法

**Comment by mrQzs** [comment]
@zhihui2015 qt的版本和编译器是什么? 还有什么分支的?

**Comment by excitedbox** [comment]
seems many people are having issues. QT has so many versions and build settings that I think it would b best to upload precompiled versions. I run QT6 already and downloading an old version not only takes up a ton of space but someone with a slow or metered connection might not have that option.

**Comment by mrQzs** [comment]
![QtSetting](https://user-images.githubusercontent.com/37052865/116015947-b0a23a80-a66d-11eb-8a50-29ca891a8d77.png)
@excitedbox  In the dev-v7 branch, this configuration can be compiled through both win7 and win10.

**Comment by mrQzs** [comment]
![Xnip2021-04-26_09-53-59](https://user-images.githubusercontent.com/37052865/116019312-85701900-a676-11eb-8e70-45df873e94e1.jpg)
ubuntu, also ok

**Comment by mrQzs** [comment]
![Xnip2021-04-27_09-57-09](https://user-images.githubusercontent.com/37052865/116173418-23c7b180-a73f-11eb-9e53-daf3b777263b.jpg)
![Xnip2021-04-27_09-56-00](https://user-images.githubusercontent.com/37052865/116173424-24f8de80-a73f-11eb-894e-d1a6b15601a9.jpg)

macos , ok~

**Comment by excitedbox** [comment]
Part of the problem is the Chinese character set. It throws about 850 warnings for being too large. Then I get between 4-18 errors depending on what settings I put in/ change

I get QHASH incomplete Type errors for m_index and m_name, and QSTRING missing sprintf (color picker) as a member with the suggestion of asprintf. There are a few other errors as well and when I fix these it starts throwing other errors.

When I fix the sprintf error I get a few mouse key incomplete type errors.

I can't spend a full day downloading an outdated version of QT. Seems pretty easy to upload a precompiled windows binary instead.

**Comment by mrQzs** [comment]
@excitedbox  
[LVGLBuilder.zip](https://github.com/CURTLab/LVGLBuilder/files/6410984/LVGLBuilder.zip)
[exeneedthis.zip](https://github.com/CURTLab/LVGLBuilder/files/6410985/exeneedthis.zip)
I uploaded a 64-bit binary program and the components needed to run it, compiled based on the msvc2015-64 compiler.

**Comment by excitedbox** [comment]
Iol I just got it running with 5.15 by adding `#include <QKeyEvent>` and `#include <QMouseEvent>` to 2 files and fixing the sprintf.

Thanks I will download yours just in case there are still bugs.
