### ISSUE TITLE
Version 7

### ISSUE THREAD

**Issue by mmt-10** [CURTLab/LVGLBuilder#7]
will you support version 7?

**Comment by mrQzs** [comment]
https://github.com/mrQzs/LVGLBuilder 
I upgraded the version to lvgl7.10. I have finished displaying some components and can operate them, but I haven't started to export the C source code.

**Comment by mrQzs** [comment]
![Snipaste_2021-02-12_23-29-11](https://user-images.githubusercontent.com/37052865/107787629-5261fd00-6d8a-11eb-806e-efc1bca87334.png)

**Comment by mrQzs** [comment]
![Snipaste_2021-02-12_23-33-27](https://user-images.githubusercontent.com/37052865/107788135-0499c480-6d8b-11eb-920d-a3668cc3bb21.png)
![Snipaste_2021-02-12_23-33-51](https://user-images.githubusercontent.com/37052865/107788146-0794b500-6d8b-11eb-9bb7-96d6f1d53bb0.png)
![Snipaste_2021-02-12_23-34-53](https://user-images.githubusercontent.com/37052865/107788147-082d4b80-6d8b-11eb-81c1-8f127f8cb050.png)
![Snipaste_2021-02-12_23-35-10](https://user-images.githubusercontent.com/37052865/107788149-095e7880-6d8b-11eb-9d94-130719d9873c.png)

**Comment by CURTLab** [comment]
Looks good! I wanted to do a branch for LVGL 7.x, but the property code needs to be refactored and it would be better if my code is more flexible.

**Comment by mrQzs** [comment]
Lvgl7. X component attributes are divided into states and parts, lvgl6. X component attributes are divided into multiple styles.Moreover, lvgl7. X has many attributes, each attribute corresponds to each state and each part, so the components of lvgl7. X can be more flexible and beautiful.Just export the function of the code needs a lot of changes, but the idea is the same as before, compared with the original attribute, only export the changed attribute code

**Comment by mrQzs** [comment]
Property template class does not need to specify a get function, because some set functions do not have a corresponding get function. In addition, the set function of some components needs a third parameter, but the current template class does not support it, and there is no corresponding get function for these functions...

**Comment by mrQzs** [comment]
![Snipaste_2021-02-19_16-50-04](https://user-images.githubusercontent.com/37052865/108481960-ce50cd80-72d3-11eb-9061-0aa8bc93c3e9.png)

**Comment by CURTLab** [comment]
I know but therefore I used inheritance for Properties. I also thought about describtor files for widgets:

```json
{
    "widgets": [
        {"name": "Arc",
         "class": "lv_arc",
         "properties": [
                { "name": "start_angle", "params": [{"name": "start", "type": "u16"}] },
                { "name": "end_angle", "params": [{"name": "end", "type": "u16"}] },
                { "name": "angles", "params": [{"name": "start", "type": "u16"}, {"name": "end", "type": "u16"}] },
                { "name": "bg_start_angle", "params": [{"name": "start", "type": "u16"}] },
                { "name": "bg_end_angle", "params": [{"name": "end", "type": "u16"}] },
                { "name": "bg_angles", "params": [{"name": "start", "type": "u16"}, {"name": "end", "type": "u16"}] },
                { "name": "rotation", "params": [{"name": "rotation_angle", "type": "u16"}] },
                { "name": "type", "params": [{"name": "type", "type": "enum", "enum": ["LV_ARC_TYPE_NORMAL", "LV_ARC_TYPE_SYMMETRIC", "LV_ARC_TYPE_REVERSE"]}] },
            ]
        }
    ]
}
```

**Comment by mrQzs** [comment]
This method looks good, and it's convenient for people who are involved in writing code.
Your template class design is very good, only a few cases do not apply.

**Comment by CURTLab** [comment]
@mrQzs I have not much time at the moment, but would you be intereseted to cooperate on the LVGL Builder? Maybe we can make a branch for the 7.x version based on your success?

**Comment by mrQzs** [comment]
@CURTLab  No problem, but the original function of saving files and reading files need to be reconstructed, and the function of exporting code is still under verification.

**Comment by mrQzs** [comment]
![Snipaste_2021-02-22_18-47-54](https://user-images.githubusercontent.com/37052865/108698396-0dcf2200-753f-11eb-9af2-ba8f54f8555b.png)
![Snipaste_2021-02-22_18-49-06](https://user-images.githubusercontent.com/37052865/108698412-132c6c80-753f-11eb-828e-1891f12bbc7a.png)
![Snipaste_2021-02-22_18-49-35](https://user-images.githubusercontent.com/37052865/108698415-14f63000-753f-11eb-8064-b214146ab3c2.png)
![Snipaste_2021-02-22_18-50-48](https://user-images.githubusercontent.com/37052865/108698418-16275d00-753f-11eb-8e2b-a5a61195c1cc.png)
![16139910988073](https://user-images.githubusercontent.com/37052865/108698429-17588a00-753f-11eb-8367-e7ca642693ee.png)

**Comment by mrQzs** [comment]
I designed a class, which can support any number of parameters and modify the specified object.

**Comment by mrQzs** [comment]
new UI,LOL
![Snipaste_2021-02-23_20-17-31](https://user-images.githubusercontent.com/37052865/108843636-ec8d3500-7615-11eb-9c97-51a9fbb6d07f.png)
![Uploading Snipaste_2021-02-23_20-26-02.png…]()

**Comment by mrQzs** [comment]
![Snipaste_2021-02-23_20-26-02](https://user-images.githubusercontent.com/37052865/108844091-97055800-7616-11eb-8b85-279b4db7fac7.png)

**Comment by mrQzs** [comment]
multiple pages
![Snipaste_2021-02-24_11-42-44](https://user-images.githubusercontent.com/37052865/108944512-d921ae80-7695-11eb-856a-e442d59a6e78.png)
![Snipaste_2021-02-24_11-43-01](https://user-images.githubusercontent.com/37052865/108944523-dcb53580-7695-11eb-86ca-c924609d4dad.png)

**Comment by mrQzs** [comment]
![Snipaste_2021-02-24_19-02-58](https://user-images.githubusercontent.com/37052865/108991730-68998280-76d3-11eb-8a3f-a15038a18087.png)

**Comment by mrQzs** [comment]
@CURTLab  If you have time later, you can design lvglcore and widgets as a class. In the case of multiple pages, the code will be very simple.

**Comment by CURTLab** [comment]
@mrQzs Sure, please push your progress into dev-v7 so I can have a look.

**Comment by mrQzs** [comment]
![Snipaste_2021-02-24_19-58-08](https://user-images.githubusercontent.com/37052865/108997897-25dba880-76db-11eb-8a60-dfe15cec89f5.png)
![Snipaste_2021-02-24_19-58-21](https://user-images.githubusercontent.com/37052865/108997905-27a56c00-76db-11eb-97e5-80df47b6318d.png)
![Snipaste_2021-02-24_19-58-59](https://user-images.githubusercontent.com/37052865/108997908-283e0280-76db-11eb-9761-7e33383ffe01.png)
![Snipaste_2021-02-24_19-59-37](https://user-images.githubusercontent.com/37052865/108997909-28d69900-76db-11eb-9b7b-a60d301b6995.png)
![Snipaste_2021-02-24_19-59-48](https://user-images.githubusercontent.com/37052865/108997912-28d69900-76db-11eb-9e8b-30a5e14a0a62.png)

This function of Widget is actually redundant, because I directly read the attributes of the obj style instead of loading the style.But I directly modify the style of the obj object, there are always problems, such as the second time it takes effect, or the style of the same type of object will change the same.There is another problem. I also thought about obtaining the original style, but the localstyle obtained through the objgetstyle function is actually not the original style, so in the end I designed it like that, and I must add the updateDate function to modify the style attributes to change in real time.

**Comment by mrQzs** [comment]
The official qt document recommends using the part of the code that is not commented in the picture, because the Chinese text cannot be displayed in other ways.

![Snipaste_2021-02-26_10-00-32](https://user-images.githubusercontent.com/37052865/109245087-cdabc000-781a-11eb-8a59-63de8ba8108a.png)
![Snipaste_2021-02-26_10-01-29](https://user-images.githubusercontent.com/37052865/109245099-d2707400-781a-11eb-965e-1c83eb4a7a14.png)
![Snipaste_2021-02-26_10-01-19](https://user-images.githubusercontent.com/37052865/109245107-d43a3780-781a-11eb-8147-b24ae70138fe.png)
![Snipaste_2021-02-26_10-09-13](https://user-images.githubusercontent.com/37052865/109245114-d603fb00-781a-11eb-8fc8-fcec240dd5d7.png)

**Comment by CURTLab** [comment]
I was thinking about unit test to catch such errors. String handling is not easy. Could you send me an example project file with as many Chinese text as possible?

**Comment by mrQzs** [comment]
@CURTLab   What kind of project file you are talking about. Can you describe it in detail?

**Comment by mrQzs** [comment]
![Snipaste_2021-02-26_16-50-42](https://user-images.githubusercontent.com/37052865/109279616-ed5fda00-7854-11eb-94b4-eb119c20f104.png)
The new interface to add series

**Comment by CURTLab** [comment]
@mrQzs A JSON project from the LVGLBuilder.

**Comment by mrQzs** [comment]
No problem, after I complete the save function, I can give you a test case in Chinese.

**Comment by mrQzs** [comment]
![Snipaste_2021-02-26_17-13-10](https://user-images.githubusercontent.com/37052865/109281259-0ec1c580-7857-11eb-8725-d49b6009c0b7.png)
![6f88fb017044d4194be7cff94e096700](https://user-images.githubusercontent.com/37052865/109281268-12554c80-7857-11eb-8a99-e3ecb955a2d6.jpg)
In my project, I added Google's breakpad, but after the program crashed, because the debugging information file has not been generated, it is not possible to locate which line of code has a problem.
After I have completed most of the functions, I am going to add this breakpad to dev-7

**Comment by mrQzs** [comment]
![Snipaste_2021-03-03_12-08-21](https://user-images.githubusercontent.com/37052865/109752810-0d5c1880-7c1c-11eb-854f-f143dca4a934.png)
![Snipaste_2021-03-03_12-12-45](https://user-images.githubusercontent.com/37052865/109752813-0df4af00-7c1c-11eb-996f-ca753cfea7a3.png)
![Snipaste_2021-03-03_12-14-14](https://user-images.githubusercontent.com/37052865/109752816-10570900-7c1c-11eb-96bf-168666e6ddcb.png)
![Snipaste_2021-03-03_12-23-17](https://user-images.githubusercontent.com/37052865/109752822-11883600-7c1c-11eb-9c12-37b0b6bdba4d.png)
I found that when an object has a parent object, the coordinate setting will be wrong.
The first problem is that the actual size of the parent object is wrong, and the second problem is that the coordinates set by the user do not need to subtract the offset.
When I tried to get the actual size of the page, I found that the second time I got it was correct, but I'm not sure if other objects are the same, so I used m_object->parent()->obj() to handle it.

**Comment by mrQzs** [comment]
![企业微信截图_16147679678073](https://user-images.githubusercontent.com/37052865/109798964-5f219480-7c56-11eb-8f4e-de57fd321456.png)
Finally understand why the size of the page is 480-14-14, because the padding attribute affects the actual size...

**Comment by mrQzs** [comment]
![Snipaste_2021-03-05_10-26-59](https://user-images.githubusercontent.com/37052865/110091574-8f427200-7dd3-11eb-9732-fd3886202570.png)
![Snipaste_2021-03-05_10-27-15](https://user-images.githubusercontent.com/37052865/110091584-923d6280-7dd3-11eb-94cc-d6fcd45d5bc9.png)
![Snipaste_2021-03-05_10-49-39](https://user-images.githubusercontent.com/37052865/110091589-92d5f900-7dd3-11eb-8403-24ce4e9d0994.png)
![6e42c4f6765f9834c535e3ad058f0cc8](https://user-images.githubusercontent.com/37052865/110091594-936e8f80-7dd3-11eb-8901-237bebf31275.jpg)
![37e1b3e6107d482d0a6b0af973655d36](https://user-images.githubusercontent.com/37052865/110091596-94072600-7dd3-11eb-8a38-6deee3662d0d.jpg)
I have implemented the save and read function, and I have also realized the automatic compilation and distribution of the program to the development board, but because it is now a company's product, I cannot share this function at the moment.

**Comment by mrQzs** [comment]
@CURTLab  If you want to test, you need the Chinese font under lvgl/font/ in my branch, chinese_16.c file.
Because there is a problem with the design of tabview, the file containing Chinese cannot be loaded. So I need to spend some time to solve it. And I found that all the same objects share the one attribute object, but this memory-saving design is currently not applicable to lvgl7, so I changed this design.
[chinese.zip](https://github.com/CURTLab/LVGLBuilder/files/6089343/chinese.zip)
![Snipaste_2021-03-05_16-50-59](https://user-images.githubusercontent.com/37052865/110092173-40e1a300-7dd4-11eb-8545-fb3624446e2e.png)
![Snipaste_2021-03-05_16-59-57](https://user-images.githubusercontent.com/37052865/110092181-43dc9380-7dd4-11eb-83ce-4573659ac3c6.png)

**Comment by CURTLab** [comment]
@mrQzs Looks very nice! Congratulations!

**Comment by mrQzs** [comment]
![Snipaste_2021-03-06_17-27-32](https://user-images.githubusercontent.com/37052865/110202208-1bbb6600-7ea2-11eb-8060-b0484f867161.png)
Thank you, there is a chinese.lvgl in the dev-v7 branch, and the information of the widgets that need to display Chinese are stored in it.
